# Generated by Django 3.2.9 on 2021-11-09 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('contacto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mercancia', models.TextField()),
                ('Contrato', models.TextField()),
                ('Fecha_Solicitud', models.DateTimeField()),
                ('Fecha_Inspeccion', models.DateTimeField()),
                ('Crea_Solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.TextField()),
                ('fecha_firma', models.DateTimeField()),
                ('periodo', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo_empresa', models.TextField(choices=[('Empresas Mixtas', 'Empresas Mixtas'), ('Empresas 100% Cubanas', 'Empresas 100% Cubanas'), ('TCP', 'TCP'), ('CNA', 'CNA'), ('Empresa Extranjera', 'Empresa Extranjera')])),
                ('id_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
        ),
    ]
