# Generated by Django 3.2.9 on 2021-11-29 19:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=15)),
                ('catidad', models.DecimalField(decimal_places=2, max_digits=11)),
                ('producto', models.TextField(max_length=15)),
                ('bl', models.TextField(max_length=20)),
                ('manifiesto', models.TextField(max_length=15)),
            ],
            options={
                'verbose_name': 'Buque',
                'verbose_name_plural': 'Buques',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.TextField(max_length=7)),
                ('fechafirma', models.DateField()),
                ('periodo', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipo_empresa', models.TextField(choices=[('Empresas Mixtas', 'Empresas Mixtas'), ('Empresas 100% Cubanas', 'Empresas 100% Cubanas'), ('TCP', 'TCP'), ('CNA', 'CNA'), ('Empresa Extranjera', 'Empresa Extranjera')])),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(max_length=10)),
                ('dimenciones', models.TextField(choices=[('20 pies', '20 pies'), ('40 pies', '40 pies')])),
                ('cantidad', models.BigIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=9)),
                ('embalaje', models.TextField(max_length=50)),
                ('estiba', models.TextField(max_length=50, null=True)),
                ('marca', models.TextField(max_length=50)),
                ('mercancia', models.TextField(max_length=15)),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('direccion', models.TextField(max_length=100)),
                ('codigo_one', models.IntegerField(verbose_name=django.db.models.fields.related.ForeignKey)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.TextField(choices=[('Sobrante', 'Sobrante'), ('Faltante', 'Faltante'), ('Averias', 'Averias')])),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.BigIntegerField(verbose_name=django.db.models.fields.related.ForeignKey)),
                ('nombre', models.TextField(max_length=10)),
                ('apellidos', models.TextField(max_length=20)),
                ('cargo', models.TextField(max_length=25)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.EmailField(max_length=25)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
            options={
                'verbose_name': 'Receptor',
                'verbose_name_plural': 'Receptores',
            },
        ),
        migrations.CreateModel(
            name='Sello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_sello', models.TextField()),
                ('material', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('tipo_servicio', models.TextField(choices=[('buque', 'Buques'), ('contenedor', 'Contenedores')])),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.TextField(choices=[('Origen', 'Origen'), ('Destino', 'Destino')], null=True)),
                ('medio', models.TextField(choices=[('buque', 'Buques'), ('contenedor', 'Contenedores')], default='Buques')),
                ('contrato', models.TextField(max_length=15, verbose_name='Contrato')),
                ('fecha_Solicitud', models.DateField(verbose_name='Fecha de la Solicitud')),
                ('fecha_Inspeccion', models.DateField(verbose_name='Fecha de la Inspeccion')),
                ('crea_Solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.persona', verbose_name='Persona')),
                ('id_buque', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.buque', verbose_name='Buque')),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.cliente', verbose_name='Cliente')),
                ('id_comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.comprador', verbose_name='Comprador')),
                ('id_contenedor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.contenedor', verbose_name='Contenedor')),
                ('id_receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.receptor', verbose_name='Receptor')),
                ('id_vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.vendedor', verbose_name='Vendedor')),
                ('servicio', models.ManyToManyField(null=True, to='Operaciones.Servicios', verbose_name='Servicios')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_orden', models.TextField(verbose_name=django.db.models.fields.related.ForeignKey)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.solicitud')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='operaciones')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Operaciones.orden')),
            ],
        ),
        migrations.AddField(
            model_name='comprador',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa'),
        ),
    ]
