# Generated by Django 3.2.9 on 2021-11-09 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0002_auto_20211109_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='comprador',
            options={'verbose_name': 'Comprador', 'verbose_name_plural': 'Compradores'},
        ),
        migrations.AlterModelOptions(
            name='contenedor',
            options={'verbose_name': 'Contenedor', 'verbose_name_plural': 'Contenedores'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='receptor',
            options={'verbose_name': 'Receptor', 'verbose_name_plural': 'Receptores'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='id_ervicios',
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='marca',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.TextField(max_length=25),
        ),
        migrations.CreateModel(
            name='SoliServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Operaciones.servicios')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Operaciones.solicitud')),
            ],
        ),
    ]
