# Generated by Django 3.2.9 on 2021-11-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0003_auto_20211109_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='mercancia',
        ),
    ]
