# Generated by Django 3.2.9 on 2021-11-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0004_remove_solicitud_mercancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='servicio',
            field=models.ManyToManyField(to='Operaciones.Servicios'),
        ),
        migrations.DeleteModel(
            name='SoliServicios',
        ),
    ]
