# Generated by Django 3.2.9 on 2021-11-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0005_auto_20211109_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='contrato',
            field=models.TextField(max_length=15, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_Inspeccion',
            field=models.DateField(verbose_name='Fecha de la Inspeccion'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_Solicitud',
            field=models.DateField(verbose_name='Fecha de la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.comprador', verbose_name='Comprador'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_contendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.receptor', verbose_name='Receptor'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='servicio',
            field=models.ManyToManyField(to='Operaciones.Servicios', verbose_name='Servicios'),
        ),
    ]
