# Generated by Django 3.2.9 on 2021-11-11 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0006_auto_20211109_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=10)),
                ('apellidos', models.TextField(max_length=20)),
                ('cargo', models.TextField(max_length=25)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=25)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_one',
            field=models.IntegerField(default=60455, verbose_name=django.db.models.fields.related.ForeignKey),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.TextField(max_length=25),
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
        migrations.AddField(
            model_name='empresa',
            name='representante',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='crea_Solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.persona', verbose_name='Persona'),
            preserve_default=False,
        ),
    ]
