# Generated by Django 3.2.9 on 2021-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0010_auto_20211115_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.TextField(choices=[('Sobrante', 'Sobrante'), ('Faltante', 'Faltante'), ('Averias', 'Averias')])),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_sello', models.TextField()),
                ('material', models.TextField()),
            ],
        ),
    ]
