# Generated by Django 3.2.9 on 2021-11-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0011_incidencia_sello'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='medio',
            field=models.TextField(choices=[('Buques', 'Buques'), ('Contenedores', 'Contenedores')], default=1),
            preserve_default=False,
        ),
    ]
