# Generated by Django 3.2.9 on 2021-11-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0012_solicitud_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='crea_Solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.comprador', verbose_name='Comprador'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.receptor', verbose_name='Receptor'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='medio',
            field=models.TextField(choices=[('Buques', 'Buques'), ('Contenedores', 'Contenedores')], default='Buques'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='servicio',
            field=models.ManyToManyField(null=True, to='Operaciones.Servicios', verbose_name='Servicios'),
        ),
    ]
