# Generated by Django 3.2.9 on 2021-11-18 18:10

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0015_orden_incidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fotos',
            field=models.ImageField(upload_to=models.TextField(verbose_name=django.db.models.fields.related.ForeignKey)),
        ),
    ]
